import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Index.module.css";
import Main from "./main";

const Home: NextPage = () => {
  return (
    <div className={styles.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </div>
  );
};

export default Home;
